export default {
  login: "vikas780",
  id: 54113274,
  node_id: "MDQ6VXNlcjU0MTEzMjc0",
  avatar_url: "https://avatars.githubusercontent.com/u/54113274?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/vikas780",
  html_url: "https://github.com/vikas780",
  followers_url: "https://api.github.com/users/vikas780/followers",
  following_url: "https://api.github.com/users/vikas780/following{/other_user}",
  gists_url: "https://api.github.com/users/vikas780/gists{/gist_id}",
  starred_url: "https://api.github.com/users/vikas780/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/vikas780/subscriptions",
  organizations_url: "https://api.github.com/users/vikas780/orgs",
  repos_url: "https://api.github.com/users/vikas780/repos",
  events_url: "https://api.github.com/users/vikas780/events{/privacy}",
  received_events_url: "https://api.github.com/users/vikas780/received_events",
  type: "User",
  site_admin: false,
  name: "Vikas ",
  company: "Shoolini university ",
  blog: "",
  location: "Himachal Pradesh, India",
  email: null,
  hireable: null,
  bio: "CSE student || Love UI designing || Full stack developer || Android developer (flutter) || React || Competitive programmer.",
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 1,
  following: 1,
  created_at: "2019-08-14T15:34:45Z",
  updated_at: "2021-05-16T07:46:54Z",
};
