export default [
  {
    login: 'atmanandsah',
    id: 12816307,
    node_id: 'MDQ6VXNlcjEyODE2MzA3',
    avatar_url: 'https://avatars.githubusercontent.com/u/12816307?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/atmanandsah',
    html_url: 'https://github.com/atmanandsah',
    followers_url: 'https://api.github.com/users/atmanandsah/followers',
    following_url:
      'https://api.github.com/users/atmanandsah/following{/other_user}',
    gists_url: 'https://api.github.com/users/atmanandsah/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/atmanandsah/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/atmanandsah/subscriptions',
    organizations_url: 'https://api.github.com/users/atmanandsah/orgs',
    repos_url: 'https://api.github.com/users/atmanandsah/repos',
    events_url: 'https://api.github.com/users/atmanandsah/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/atmanandsah/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Adarsh2908',
    id: 44540660,
    node_id: 'MDQ6VXNlcjQ0NTQwNjYw',
    avatar_url: 'https://avatars.githubusercontent.com/u/44540660?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Adarsh2908',
    html_url: 'https://github.com/Adarsh2908',
    followers_url: 'https://api.github.com/users/Adarsh2908/followers',
    following_url:
      'https://api.github.com/users/Adarsh2908/following{/other_user}',
    gists_url: 'https://api.github.com/users/Adarsh2908/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Adarsh2908/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Adarsh2908/subscriptions',
    organizations_url: 'https://api.github.com/users/Adarsh2908/orgs',
    repos_url: 'https://api.github.com/users/Adarsh2908/repos',
    events_url: 'https://api.github.com/users/Adarsh2908/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Adarsh2908/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'Prashant-1986',
    id: 56106064,
    node_id: 'MDQ6VXNlcjU2MTA2MDY0',
    avatar_url: 'https://avatars.githubusercontent.com/u/56106064?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Prashant-1986',
    html_url: 'https://github.com/Prashant-1986',
    followers_url: 'https://api.github.com/users/Prashant-1986/followers',
    following_url:
      'https://api.github.com/users/Prashant-1986/following{/other_user}',
    gists_url: 'https://api.github.com/users/Prashant-1986/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Prashant-1986/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/Prashant-1986/subscriptions',
    organizations_url: 'https://api.github.com/users/Prashant-1986/orgs',
    repos_url: 'https://api.github.com/users/Prashant-1986/repos',
    events_url: 'https://api.github.com/users/Prashant-1986/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Prashant-1986/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'uraninite',
    id: 72281205,
    node_id: 'MDQ6VXNlcjcyMjgxMjA1',
    avatar_url: 'https://avatars.githubusercontent.com/u/72281205?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/uraninite',
    html_url: 'https://github.com/uraninite',
    followers_url: 'https://api.github.com/users/uraninite/followers',
    following_url:
      'https://api.github.com/users/uraninite/following{/other_user}',
    gists_url: 'https://api.github.com/users/uraninite/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/uraninite/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/uraninite/subscriptions',
    organizations_url: 'https://api.github.com/users/uraninite/orgs',
    repos_url: 'https://api.github.com/users/uraninite/repos',
    events_url: 'https://api.github.com/users/uraninite/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/uraninite/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ashu-9',
    id: 73665983,
    node_id: 'MDQ6VXNlcjczNjY1OTgz',
    avatar_url: 'https://avatars.githubusercontent.com/u/73665983?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ashu-9',
    html_url: 'https://github.com/ashu-9',
    followers_url: 'https://api.github.com/users/ashu-9/followers',
    following_url: 'https://api.github.com/users/ashu-9/following{/other_user}',
    gists_url: 'https://api.github.com/users/ashu-9/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ashu-9/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ashu-9/subscriptions',
    organizations_url: 'https://api.github.com/users/ashu-9/orgs',
    repos_url: 'https://api.github.com/users/ashu-9/repos',
    events_url: 'https://api.github.com/users/ashu-9/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ashu-9/received_events',
    type: 'User',
    site_admin: false,
  },
]
