export default [
  {
    login: "Adarsh2908",
    id: 44540660,
    node_id: "MDQ6VXNlcjQ0NTQwNjYw",
    avatar_url: "https://avatars.githubusercontent.com/u/44540660?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Adarsh2908",
    html_url: "https://github.com/Adarsh2908",
    followers_url: "https://api.github.com/users/Adarsh2908/followers",
    following_url:
      "https://api.github.com/users/Adarsh2908/following{/other_user}",
    gists_url: "https://api.github.com/users/Adarsh2908/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Adarsh2908/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Adarsh2908/subscriptions",
    organizations_url: "https://api.github.com/users/Adarsh2908/orgs",
    repos_url: "https://api.github.com/users/Adarsh2908/repos",
    events_url: "https://api.github.com/users/Adarsh2908/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Adarsh2908/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "JaroslawLis",
    id: 37364317,
    node_id: "MDQ6VXNlcjM3MzY0MzE3",
    avatar_url: "https://avatars0.githubusercontent.com/u/37364317?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JaroslawLis",
    html_url: "https://github.com/JaroslawLis",
    followers_url: "https://api.github.com/users/JaroslawLis/followers",
    following_url:
      "https://api.github.com/users/JaroslawLis/following{/other_user}",
    gists_url: "https://api.github.com/users/JaroslawLis/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/JaroslawLis/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/JaroslawLis/subscriptions",
    organizations_url: "https://api.github.com/users/JaroslawLis/orgs",
    repos_url: "https://api.github.com/users/JaroslawLis/repos",
    events_url: "https://api.github.com/users/JaroslawLis/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JaroslawLis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "JustinAnthonyB",
    id: 20384195,
    node_id: "MDQ6VXNlcjIwMzg0MTk1",
    avatar_url: "https://avatars2.githubusercontent.com/u/20384195?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/JustinAnthonyB",
    html_url: "https://github.com/JustinAnthonyB",
    followers_url: "https://api.github.com/users/JustinAnthonyB/followers",
    following_url:
      "https://api.github.com/users/JustinAnthonyB/following{/other_user}",
    gists_url: "https://api.github.com/users/JustinAnthonyB/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/JustinAnthonyB/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/JustinAnthonyB/subscriptions",
    organizations_url: "https://api.github.com/users/JustinAnthonyB/orgs",
    repos_url: "https://api.github.com/users/JustinAnthonyB/repos",
    events_url: "https://api.github.com/users/JustinAnthonyB/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/JustinAnthonyB/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dundja",
    id: 42780673,
    node_id: "MDQ6VXNlcjQyNzgwNjcz",
    avatar_url: "https://avatars1.githubusercontent.com/u/42780673?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dundja",
    html_url: "https://github.com/dundja",
    followers_url: "https://api.github.com/users/dundja/followers",
    following_url: "https://api.github.com/users/dundja/following{/other_user}",
    gists_url: "https://api.github.com/users/dundja/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dundja/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dundja/subscriptions",
    organizations_url: "https://api.github.com/users/dundja/orgs",
    repos_url: "https://api.github.com/users/dundja/repos",
    events_url: "https://api.github.com/users/dundja/events{/privacy}",
    received_events_url: "https://api.github.com/users/dundja/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wisemanchris92",
    id: 32992448,
    node_id: "MDQ6VXNlcjMyOTkyNDQ4",
    avatar_url: "https://avatars1.githubusercontent.com/u/32992448?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wisemanchris92",
    html_url: "https://github.com/wisemanchris92",
    followers_url: "https://api.github.com/users/wisemanchris92/followers",
    following_url:
      "https://api.github.com/users/wisemanchris92/following{/other_user}",
    gists_url: "https://api.github.com/users/wisemanchris92/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/wisemanchris92/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/wisemanchris92/subscriptions",
    organizations_url: "https://api.github.com/users/wisemanchris92/orgs",
    repos_url: "https://api.github.com/users/wisemanchris92/repos",
    events_url: "https://api.github.com/users/wisemanchris92/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/wisemanchris92/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "919971603657",
    id: 19673568,
    node_id: "MDQ6VXNlcjE5NjczNTY4",
    avatar_url: "https://avatars0.githubusercontent.com/u/19673568?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/919971603657",
    html_url: "https://github.com/919971603657",
    followers_url: "https://api.github.com/users/919971603657/followers",
    following_url:
      "https://api.github.com/users/919971603657/following{/other_user}",
    gists_url: "https://api.github.com/users/919971603657/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/919971603657/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/919971603657/subscriptions",
    organizations_url: "https://api.github.com/users/919971603657/orgs",
    repos_url: "https://api.github.com/users/919971603657/repos",
    events_url: "https://api.github.com/users/919971603657/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/919971603657/received_events",
    type: "User",
    site_admin: false,
  },
];
